version: '3'

services:
  server:
    container_name: go_server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src
    tty: true
    ports:
      - 80:8080
